/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.70
 * Generated at: 2023-10-05 04:55:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Admin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n<!doctype html>\r\n<html lang=\"en\">\r\n  <head>\r\n   \r\n    <meta charset=\"utf-8\">\r\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n\r\n \r\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css\" integrity=\"sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N\" crossorigin=\"anonymous\">\r\n<link rel=\"stylesheet\" href=\"css/Home.css\">\r\n    <title>BillingHome</title>\r\n  </head>\r\n  <body>\r\n    \r\n<nav class=\"navbar navbar-nav \" >Payment Billing System</nav>\r\n\r\n<div class=\"img-image\">\r\n<img src=\"img/banner.jpg\" alt=\"\" class=\"img-pay\">\r\n</div>\r\n\r\n\r\n<nav class=\"navbar navbar-expand-lg  \" id=\"Nav\">\r\n<div class=\"collapse navbar-collapse\">\r\n    \r\n<ul class=\"navbar nav mr-auto\">\r\n<li class=\"nav-item\">\r\n<a class=\"nav-link\"  href=\"Home.jsp\">Home </a>\r\n</li>\r\n<li class=\"nav-item\">\r\n    <a class=\"nav-link\"  href=\"#\">New Registartion </a>\r\n    </li>\r\n    <li class=\"nav-item\">\r\n        <a class=\"nav-link\"  href=\"#\">Modify Details</a>\r\n");
      out.write("        </li>\r\n        <li class=\"nav-item\">\r\n            <a class=\"nav-link\"  href=\"#\">Administration</a>\r\n            </li>\r\n            <li class=\"nav-item\">\r\n                <a class=\"nav-link\"  href=\"#\">Contact Us</a>\r\n                </li>\r\n\r\n</ul>\r\n</div>\r\n</nav>\r\n\r\n<div class=\"Administration\">\r\n    <H4>Consultant:YaraGo</H4>\r\n    <div  style=\"float: right; margin-right: 5%;\"><a href=\"\">Notice</a></div>\r\n</div>\r\n\r\n\r\n<form action=\"\">\r\n    <div class=\" Form_Form\">\r\n<label for=\"\">Username:</label>\r\n<input type=\"text\" name=\"name\" id=\"name\" placeholder=\"Username\"><br>\r\n\r\n<label for=\"\">Password:</label>\r\n<input type=\"password\" name=\"Password\" id=\"name\" placeholder=\"Password\"><br>\r\n<button  class=\"Button\" type=\"submit\">Sign in</button>\r\n</div>\r\n\r\n</form>\r\n\r\n<nav class=\"navbar navbar-nav YaraGo\" style=\"margin-top: 250px;\">Copyright 2023 All Right reserved visit more information <a href=\"\" style=\"color: yellow;\">yaragos.com</a> </nav>\r\n\r\n\r\n \r\n    <script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js\" integrity=\"sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct\" crossorigin=\"anonymous\"></script>\r\n\r\n  \r\n  </body>\r\n</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
